# generated by datamodel-codegen:
#   filename:  news_report_entity.json
#   timestamp: 2025-08-13T07:48:28+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class NewsReportEntity(BaseModel):
    id: UUID = Field(..., description='The unique identifier for a report.')
    press_release_type: str = Field(..., description='Type of press release.')
    report_date: datetime = Field(
        ..., description='The distribution or creation date of the report.'
    )
    title: str = Field(..., description='The title of the report.')
    subtitle: Optional[str] = Field(None, description='The subtitle of the report.')
    summary: Optional[str] = Field(
        None, description='The main summary of the report (optional).'
    )
    department: str = Field(..., description='The department in charge.')
    person_in_charge: str = Field(..., description='The person in charge.')
    content: List[str] = Field(..., description='The main content of the report.')
    numerical_data: Optional[List[str]] = Field(
        None, description='Optional list of numerical data.'
    )
